Unfo/Models/ViewModels/VotingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using CsQuery.Engine.PseudoClassSelectors;
using DataModel;
using DataModel.ModelInterfaces;
using OrangeJetpack.Localization;
using Unfo.App_LocalResources;
using Unfo.Core;
using Unfo.Core.GlobalClasses;
using Unfo.Models.ViewModels.CommonViewModels;
using Unfo.Models.ViewModels.Dictionaries;
using UnfoIdentitySystem.GlobalStaticClasses;

namespace Unfo.Models.ViewModels
{

    public class BaseVM
    {
        public Guid ID { get; set; }

        public BaseVM()
        {

        }

        public BaseVM(Guid id)
        {
            ID = id;
        }

        public string Localization(string fieldData, string val)
        {
            return Core.Helpers.LocalizeHelper.Localization(CurrentLocalization.Edit, fieldData, val);
        }

        public string GetLocalizeField(string field)
        {
            return Core.Helpers.LocalizeHelper.GetLocalizeField(CurrentLocalization.Edit, field);
        }
    }
    public class BaseEventVM : BaseVM
    {
        public Guid EventID { get; set; }

        public BaseEventVM()
            : base()
        {

        }

        public BaseEventVM(Guid eventID)
        {
            EventID = eventID;
        }
    }

    public class ShortVoteViewModel : BaseEventVM, IModelBuilder<Vote>
    {
        public ShortVoteViewModel(Vote vote, string lang)
        {
            Fill(vote, lang);
        }

        public ShortVoteViewModel()
        {

        }

        public ShortVoteViewModel(Guid eventId)
            : base(eventId)
        {
        }

        public void Fill(Vote vote, string lang)
        {
            try
            {
                Name = vote.Localize(lang, d => d.Name).Name;
                Description = vote.Localize(lang, d => d.Description).Description;
            }
            catch (Exception)
            {
                Name = vote.Name;
                Description = vote.Description;
            }
            ID = vote.ID;
            EventID = vote.EventID;
            IsFinished = vote.IsFinished;
            IsOnline = vote.IsOnline;
            IsOpros = vote.Type == VoteTypes.Quiz;
        }



        public Vote GetModel()
        {
            var lcName = new List<LocalizedContent>();
            var lcDescription = new List<LocalizedContent>();

            var langs = CurrentEvent.GetAccessCultures();
            foreach (var lang in langs)
            {
                if (lang.Key == CurrentLocalization.Edit)
                {
                    lcName.Add(new LocalizedContent(CurrentLocalization.Edit, Name));
                    lcDescription.Add(new LocalizedContent(CurrentLocalization.Edit, Description));
                }
                else
                {
                    lcName.Add(new LocalizedContent(lang.Key, ""));
                    lcDescription.Add(new LocalizedContent(lang.Key, ""));
                }
            }


            return new Vote()
            {
                Name = LocalizedContent.Serialize(lcName),
                Description = LocalizedContent.Serialize(lcDescription),
                EventID = EventID,
                IsOnline = IsOnline,
                IsFinished = IsFinished,
                Type = IsOpros ? VoteTypes.Quiz : VoteTypes.Vote,
                ID = ID,
            };
        }



        public Vote UpdateModel(Vote data)
        {
            var nameFields = LocalizeField(LocalizedContent.Deserialize(data.Name).ToList(), Name);
            var descriptionFields = LocalizeField(LocalizedContent.Deserialize(data.Description).ToList(), Description);

            data.Name = LocalizedContent.Serialize(nameFields);
            data.Description = LocalizedContent.Serialize(descriptionFields);
            data.EventID = EventID;
            data.IsOnline = IsOnline;
            data.IsFinished = IsFinished;
            data.Type = IsOpros ? VoteTypes.Quiz : VoteTypes.Vote;
            data.ID = ID;

            return data;
        }

        private IEnumerable<LocalizedContent> LocalizeField(ICollection<LocalizedContent> fields, string name)
        {
            bool insert = false;
            foreach (var item in fields)
            {
                if (item.Key == CurrentLocalization.Edit)
                {
                    item.Value = Name;
                    insert = true;
                }
            }
            if (!insert)
                fields.Add(new LocalizedContent(CurrentLocalization.Edit, Name));

            return fields;
        }

        [Display(ResourceType = typeof(Resources), Name = "Voting_Название_голосования")]
        public string Name { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Voting_Текст_вопроса")]
        public string Description { get; set; }

        public bool IsOnline { get; set; }

        public bool IsFinished { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Voting_Опрос")]
        public bool IsOpros { get; set; }

    }



    public class VoteViewModel : ShortVoteViewModel
    {
        public VoteViewModel(Vote vote, string lang)
        {
            Fill(vote, lang);
        }

        public VoteViewModel()
        {

        }

        public VoteViewModel(Guid eventId)
            : base(eventId)
        {
        }

        public void Fill(Vote vote, string lang)
        {
            base.Fill(vote, lang);
            if (vote.Questions != null) Questions = vote.Questions.ToList().Select(d => new VoteQuestionViewModel(d, lang)).ToList();
        }

        public int? Sum { get; set; }

        public List<VoteQuestionViewModel> Questions { get; set; }


        public IList<string> Answers { get; set; }


        public Vote GetModel()
        {
            return base.GetModel();
        }

    }

    public class VoteQuestionViewModel : BaseVM, IModelBuilder<VoteQuestion>
    {
        private Guid VoteId { get; set; }
        public string Name { get; set; }
        public int Result { get; set; }

        public VoteQuestionViewModel(VoteQuestion voteQuestion, string lang)
        {
            Fill(voteQuestion, lang);
        }

        public VoteQuestionViewModel()
        {
            ID = new Guid();
        }



        public VoteQuestionViewModel(Guid eventId)
            : base(eventId)
        {

        }

        public void Fill(VoteQuestion voteQuestion, string language)
        {
            if (voteQuestion == null) return;
            ID = voteQuestion.ID;
            VoteId = voteQuestion.VoteID;

            try
            {
                Name = voteQuestion.Localize(language, d => d.Name).Name;

            }
            catch (Exception)
            {
                Name = voteQuestion.Name;
            }
        }


        public VoteQuestion GetModel()
        {
            ID = ID;

            var langs = CurrentEvent.GetAccessCultures();
            var lcName = langs.Select(lang => lang.Key == CurrentLocalization.Edit ? new LocalizedContent(CurrentLocalization.Edit, Name) : new LocalizedContent(lang.Key, "")).ToList();


            return new VoteQuestion()
            {
                Name = LocalizedContent.Serialize(lcName),
                ID = ID,
                Description = LocalizedContent.Serialize(lcName),
            };
        }

        public VoteQuestion UpdateModel(VoteQuestion data)
        {
            var fileds = LocalizedContent.Deserialize(data.Name).ToList();
            bool insert = false;
            foreach (var item in fileds)
            {
                if (item.Key == CurrentLocalization.Edit)
                {
                    item.Value = Name;
                    insert = true;
                }
            }
            if (!insert)
                fileds.Add(new LocalizedContent(CurrentLocalization.Edit, Name));


            data.Name = LocalizedContent.Serialize(fileds);
            data.ID = ID;

            return data;
        }

        //public VoteQuestion UpdateModel(VoteQuestion modelForUpdate)
        //{
        //    modelForUpdate.Name = Localization(modelForUpdate.Name, Name);
        //    modelForUpdate.Description = Localization(modelForUpdate.Description, Name);

        //    return modelForUpdate;
        //}
    }
}

Unfo/Areas/Cabinet/Controllers/EventManagement/VotingController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using DataModel;
using Unfo.Core;
using Unfo.Core.BaseClasses;
using Unfo.Core.GlobalClasses;
using Unfo.Models.ViewModelRepositories;
using Unfo.Models.ViewModels;
using UnfoIdentitySystem.GlobalStaticClasses;

namespace Unfo.Areas.Cabinet.Controllers.EventManagement
{
    public partial class VotingController : BaseController
    {
        /// <summary>
        /// Голосования
        /// </summary>
        /// <returns></returns>
        public virtual ActionResult Index(string uid)
        {
            var data = VmRepository.Votings.GetVotes(CurrentEvent.ID);
            return View(data);
        }

        public virtual ActionResult Edit(Guid? id)
        {
            VoteViewModel data;
            if (id.HasValue && id.Value != Guid.Empty)
            {
                data = VmRepository.Votings.GetVoteWithResults(CurrentEvent.ID, id.Value);
            }
            else
            {
                var questions = new List<VoteQuestionViewModel>()
                {
                    new VoteQuestionViewModel(),
                    new VoteQuestionViewModel(),
                };

                data = new VoteViewModel(CurrentEvent.ID) {Questions = questions};
            }
          

            return View(data);
        }


        [HttpPost]
        public virtual ActionResult Edit(VoteViewModel data)
        {
            if (ModelState.IsValid)
            {
                
                

                var voteID = VmRepository.Votings.AddOrUpdate(data);
                if (CurrentEvent.GetAccessCultures().Count > 1)
                {
                    Alert.Error(true, "Голосование сохранено");
                    return RedirectToAction("Edit", new {id = voteID});
                }
                return RedirectToAction("Index");
            }

            return View(data);
        }

        [HttpGet]
        public virtual ActionResult GetVoteQuestion(string lang)
        {
            var data = new VoteQuestionViewModel();
            return PartialView(MVC.Cabinet.Shared.Views.EditorTemplates.VoteQuestionViewModel, data);
        }

        public virtual ActionResult ToogleActivate(Guid? id)
        {
            VoteViewModel data;
            if (id.HasValue && id.Value != Guid.Empty)
            {
                VmRepository.Votings.ToogleVote(id.Value);
            }

            Alert.Error(true, "Не могу найти голосование");
            return RedirectToAction("Index");
        }

        public virtual ActionResult Show(Guid id)
        {
            if (id == Guid.Empty) return RedirectToAction("Index");

            var data = VmRepository.Votings.GetVoteWithResults(CurrentEvent.ID, id);
            bool canVote = !VmRepository.Votings.HasVote(id, User.Id);
            ViewBag.CanVote = canVote;

            return View(data);
        }

        [HttpPost]
        public virtual ActionResult Delete(Guid? id)
        {
            VoteViewModel data;
            if (id.HasValue && id.Value != Guid.Empty)
            {
                VmRepository.Votings.DeleteVote(id.Value);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public virtual ActionResult Vote(Guid questionId)
        {
            var data = VmRepository.Votings.GetVoteByQuestion(questionId, CurrentLocalization.Edit);
            if (data == null && data.ID != Guid.Empty)
            {
                Alert.Error(true, "Не могу найти голосование");
                return RedirectToAction("Index");
            }

            if (!VmRepository.Votings.HasVote(questionId, User.Id))
                VmRepository.Votings.Vote(questionId, User.Id);


            return RedirectToAction("Index");
           
        }

        [HttpPost]
        public virtual ActionResult VoteWithAnswer(Guid voteID, string answer)
        {
            if (voteID != Guid.Empty && !String.IsNullOrEmpty(answer))
                VmRepository.Votings.VoteWithAnswer(voteID, answer);

            return RedirectToAction("Index", new { id = voteID });
        }
    }
    
}

Unfo/Areas/Cabinet/Views/Voting/Edit.cshtml
@using System.Web.Optimization
@using Unfo.Core
@using Unfo.Core.GlobalClasses
@using UnfoIdentitySystem.GlobalStaticClasses
@model Unfo.Models.ViewModels.VoteViewModel
@{

    ViewBag.Title = Model.ID != Guid.Empty ? Resources.c_Edit + " " + Model.Name : Resources.Voting_New_Vote;
    Layout = "~/Areas/Cabinet/Views/Shared/_Layout.cshtml";
    
    var cul = CurrentEvent.GetAccessCultures();
    var activeLang = Request.Cookies[CurrentLocalization.CookieName] == null ? "ru" : Request.Cookies[CurrentLocalization.CookieName].Value;
}

@Html.Partial("_LanguageTabs")

@Html.ShowAlert(true)

@using (Html.BeginForm())
{
    @Html.ValidationSummary(false)

    <fieldset class="form-horizontal">
        @Html.EditorFor(d => Model, MVC.Cabinet.Shared.Views.EditorTemplates.VoteViewModel)
        <div class="form-actions">
            <button type="submit" class="btn btn-success">@(Resources.c_Save)</button>

            @Html.ActionLink(Resources.c_Back_To_List, MVC.Cabinet.Voting.Index(), new { @class = "btn btn-default" })
        </div>
    </fieldset>
}


@section Scripts {
    <script type="text/javascript">
        $(function() {

            $('#addQuestion').click(function() {
                if (!$(this).hasClass("disabled")) {
                    var url = $(this).attr('data-url');

                    getQuestionForLang(url);
                    return false;
                }
            });

            if ($('#IsOpros').attr("checked")) {
                $('#questions_list').hide();
            }

            $('#IsOpros').on("change", function() {
                $('#questions_list').toggle();
            });

            function getQuestionForLang(url) {
                $.get(url, function(html) {
                    $('#questions_list ul').append(html);
                });
            }

        });

    </script>
}

Unfo/Areas/Cabinet/Views/Voting/Index.cshtml
@using System.Web.Optimization
@using Unfo.Core
@model IEnumerable<Unfo.Models.ViewModels.ShortVoteViewModel>
@{
    ViewBag.Title = "Голосования и опросы";
    Layout = "~/Areas/Cabinet/Views/Shared/_Layout.cshtml";
    ViewBag.BodyId = "votings";
}


@section ExtendedHeaderBlock
{
    <div class="menubar fixed">
        <div class="sidebar-toggler visible-xs">
            <i class="ion-navicon"></i>
        </div>
        <div class="page-title"> @(Resources.t_Голосования_опросы) </div>

        @Html.ActionLink(Resources.c_Add, "Edit", null, new {@class = "btn btn-success pull-right"})
    </div>
}



@Html.Partial("_LanguageTabs")

@Html.ShowAlert(true)


<table class="table table-striped">
    <caption>
    </caption>
    <thead>
        <tr>
            <th>
                @(Resources.c_Title)
            </th>

            <th>
               
            </th>
        </tr>
    </thead>
    @foreach (var model in Model)
    {
        <tr class="@(model.IsOnline && !model.IsFinished ? "success" : "")">
            <td>
                @(model.Name)
            </td>
            <td></td>
            <td style="text-align: right;">

                @{
        if (model.IsOnline || model.IsFinished)
        {
            <a class="btn btn-default " href="@(Url.Action("Show", "Voting", new {id = model.ID, type = 1}))"> <span class="glyphicon glyphicon-eye-open"></span></a>
        }
                    @Html.ActionLink(Resources.c_Edit, "Edit", new { id = model.ID }, new { @class = "btn btn-default", @style = "margin-right: 10px; " })

                    if (!model.IsFinished && model.IsOnline)
                    {
                        @Html.ActionLink(Resources.c_Finish, "ToogleActivate", new { id = model.ID }, new { @class = "btn btn-warning", @style = "margin-right: 10px; width: 120px;" })
                    }
                    else
                    {
                        @(model.IsOnline ?
                                  Html.ActionLink(Resources.c_Continue, "ToogleActivate", new { id = model.ID }, new { @class = "btn btn-success", @style = "margin-right: 10px; width: 120px;" })
                                  : Html.ActionLink(Resources.c_Start, "ToogleActivate", new { id = model.ID }, new { @class = "btn btn-success", @style = "margin-right: 10px; width: 120px;" }))
                    }


                    using (Html.BeginForm("Delete", "Voting", FormMethod.Post, new {style = "display: inline-block;"}))
                    {
                        @Html.Hidden("Id", model.ID)

                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    }

                }
            </td>
        </tr>
    }
</table>

Unfo/Areas/Cabinet/Views/Voting/Show.cshtml
@using System.Web.Optimization
@using Unfo.Core
@using Unfo.Core.GlobalClasses
@using UnfoIdentitySystem.GlobalStaticClasses
@model Unfo.Models.ViewModels.VoteViewModel
@{

    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";

    var cul = CurrentEvent.GetAccessCultures();
    var activeLang = Request.Cookies[CurrentLocalization.CookieName] == null ? "ru" : Request.Cookies[CurrentLocalization.CookieName].Value;
    var votingUrl = Url.Action("Vote", "Voting", new { id = Model.ID });
}


@functions {

    public static string GetPercent(int sum, int? result)
    {
        if (sum == 0) return "0";
        if (result == null) return "0";
        double d = (double)(100 * sum) / result.Value;
        return String.Format(Math.Abs(d % 1) < 0 ? "{0:0}" : "{0:0.0}", d);
    }

    public static int GetIntPercent(int sum, int? result)
    {
        if (sum == 0) return 0;
        if (result == null) return 0;
        double d = (double)(100 * sum) / result.Value;
        return (int)d;
    }

}

<div id="show-voting">

    @if (!ViewBag.CanVote)
    {
        <h4> Голосование - @(Model.Name) </h4>
        <p> @(Model.Description) </p>

        if (!Model.IsOpros)
        {
            foreach (var item in Model.Questions)
            {
                if (!string.IsNullOrEmpty(item.Name))
                {
                    <div class="results-block-@(item.ID)">

                        <span> @(item.Name) </span>
                        <div style="clear: both;"> </div>

                        @( GetIntPercent(item.Result, Model.Sum) + "%")

                        <div class="progress">
                            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: @( GetIntPercent(item.Result, Model.Sum) + "%")">  </div>
                           
                        </div>
                    </div>
                }
            }

        }
        else
        {
            foreach (var item in Model.Answers)
            {
                <p> @item </p>
            }
        }

        <div style="clear: both"> <a href="@(Url.Action("Index", "Voting", new {  }))" class="btn btn-warning"> Назад</a> </div>
    }
    else
    {
        <h4 style="color: #ff8c00"> @(Model.Name) </h4>
        <p>@(Model.Description)</p>

        <div class="questions-list">

            @if (!Model.IsOpros)
            {
                foreach (var item in Model.Questions)
                {
                    if (!string.IsNullOrEmpty(item.Name))
                    {
                        using (Html.BeginForm("Vote", "Voting", FormMethod.Post, null))
                        {
                            var questionID = item.ID;

                            @Html.Hidden("questionId", questionID)
                            <button type="submit" class="btn btn-success"> @(item.Name)</button>
                        }
                        <br />
                    }
                }

                <div> <a href="@(Url.Action("Index", "Voting", new { }))" class="btn btn-warning"> ← Назад</a> </div>
            }
            else
            {
                using (Html.BeginForm("VoteWithAnswer", "Voting"))
                {
                    @Html.ValidationSummary(false)

                    <div style="display: none;">
                        <input class="" id="voteID" name="voteID" type="text" value="@(Model.ID)">
                    </div>
                    <textarea class="" id="answer" name="answer" placeholder="Ваш ответ" type="text" rows="6" value="" style="width: 100%; height: 200px; "></textarea>
                    <br>
                    <div style="float: left;"> <a href="@(Url.Action("Index", "Voting", new { }))" class="btn btn-warning"> ← Назад</a> </div>
                    <input type="submit" class="btn btn-success" value="Отправить" style="float: right;">
                }
            }
        </div>
        <div style="clear: both;"></div>
    }

</div>

Unfo/Areas/Cabinet/Views/Voting/VoteQuestionViewModel.cshtml
@using System.Globalization
@using HtmlHelpers.BeginCollectionItem
@using Unfo.Core.GlobalClasses
@using UnfoIdentitySystem.GlobalStaticClasses
@model Unfo.Models.ViewModels.VoteQuestionViewModel
@{
    var cultures = CurrentEvent.GetAccessCultures();
    var lang = ViewData["language"];
    var formIndex = ViewData["formIndex"];
}


<li>
    @using (Html.BeginCollectionItem("questions"))
    {
        @Html.EditorFor(d => Model, MVC.Cabinet.Shared.Views.EditorTemplates.VoteQuestionViewModel)
    }
</li>